spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/deneme?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        id:
          new_generator_mappings: false
    show-sql: true

server:
  port: 8080 # This is the default port anyway, but you can change it here

